%% Code generated by libero. DO NOT EDIT.
%%
%% Pre-registers all atoms that may appear in client ETF payloads,
%% so binary_to_term([safe]) can decode them without rejecting unknown
%% atoms. Includes framework atoms, handler function names, bare
%% constructor names, and the 10-char hex wire-identity hashes that
%% the per-type transformer functions emit on the wire.
%%
%% ensure/0 uses persistent_term as a one-shot guard so the
%% binary_to_atom calls only run once per VM lifetime.

-module(generated@public@rpc_atoms).
-export([ensure/0, encode_push_frame/2, json_encode_push_value/2]).

ensure() ->
    case persistent_term:get({?MODULE, done}, false) of
        true -> nil;
        false -> do_ensure()
    end.

do_ensure() ->
    lists:foreach(fun(B) -> binary_to_atom(B) end, [
        <<"003511dd1c">>,
        <<"10251ccd57">>,
        <<"19ae752434">>,
        <<"3adf004bda">>,
        <<"42a9f6fcde">>,
        <<"45ac7f3cba">>,
        <<"decode_error">>,
        <<"e4ff4f2689">>,
        <<"error">>,
        <<"false">>,
        <<"increment">>,
        <<"increment_by">>,
        <<"increment_result">>,
        <<"internal_error">>,
        <<"malformed_request">>,
        <<"model">>,
        <<"nil">>,
        <<"none">>,
        <<"ok">>,
        <<"server_increment">>,
        <<"server_increment_by">>,
        <<"some">>,
        <<"true">>,
        <<"unknown_function">>,
        <<"updated">>
    ]),
    persistent_term:put({libero, wire_module}, 'generated@public@rpc_wire'),
        persistent_term:put({libero, push_frame_module}, 'generated@public@rpc_atoms'),
    persistent_term:put({libero, json_wire_module}, 'generated@public@protocol_wire'),
    persistent_term:put({?MODULE, done}, true),
    nil.


%% Push dispatch: route page tag to the correct typed encoder.
json_encode_push_value(Page, Msg) ->
    case Page of
    <<"Public">> -> 'generated@public@json_codecs':'json_encode_public_pages_home___to_client'(Msg);
    <<"PublicNotifications">> -> 'generated@public@json_codecs':'json_encode_public_pages_notifications___to_client'(Msg);
    Page -> error({no_json_push_encoder, Page})
    end.

%% Single push-frame facade called by rally_runtime_ffi.
encode_push_frame(Page, Msg) ->
    JsonValue = json_encode_push_value(Page, Msg),
    JsonWireMod = persistent_term:get({libero, json_wire_module}),
    JsonWireMod:encode_push(Page, JsonValue).
