name = "lando"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
glance = ">= 1.0.0 and < 2.0.0"
glexer = ">= 2.0.0 and < 3.0.0"
lustre = ">= 5.6.0 and < 7.0.0"
marmot = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
tom = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
