%% Code generated by libero. DO NOT EDIT.
%%
%% Pre-registers all atoms that may appear in client ETF payloads,
%% so binary_to_term([safe]) can decode them without rejecting unknown
%% atoms. Includes framework atoms, handler function names, bare
%% constructor names, and the 10-char hex wire-identity hashes that
%% the per-type transformer functions emit on the wire.
%%
%% ensure/0 uses persistent_term as a one-shot guard so the
%% binary_to_atom calls only run once per VM lifetime.

-module(generated@public@rpc_atoms).
-export([ensure/0]).

ensure() ->
    case persistent_term:get({?MODULE, done}, false) of
        true -> nil;
        false -> do_ensure()
    end.

do_ensure() ->
    lists:foreach(fun(B) -> binary_to_atom(B) end, [
        <<"003511dd1c">>,
        <<"10251ccd57">>,
        <<"3adf004bda">>,
        <<"decode_error">>,
        <<"e4ff4f2689">>,
        <<"error">>,
        <<"false">>,
        <<"increment">>,
        <<"increment_by">>,
        <<"increment_result">>,
        <<"internal_error">>,
        <<"malformed_request">>,
        <<"model">>,
        <<"nil">>,
        <<"none">>,
        <<"ok">>,
        <<"server_increment">>,
        <<"server_increment_by">>,
        <<"some">>,
        <<"true">>,
        <<"unknown_function">>
    ]),
    persistent_term:put({libero, wire_module}, 'generated@public@rpc_wire'),
    persistent_term:put({?MODULE, done}, true),
    nil.
