name = "realworld"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
lando = { path = "../.." }
lustre = ">= 5.6.0 and < 7.0.0"
marmot = { path = "../../../marmot" }
mist = ">= 6.0.0 and < 7.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.0.0 and < 2.0.0"

[tools.lando]
pages_root = "src/pages"
output_route = "src/generated/router.gleam"
output_dispatch = "src/generated/page_dispatch.gleam"
output_server_dispatch = "src/generated/server_dispatch.gleam"
output_ssr = "src/generated/ssr_handler.gleam"
output_ws = "src/generated/ws_handler.gleam"
sql_dir = "src/sql"
client_root = "client"

[tools.marmot]
database = "app.db"
sql_dir = "src/sql"
output = "src/generated/sql"
