name = "realworld_cli"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.69.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
libero = { path = "../../../../libero" }
argv = ">= 1.0.0 and < 2.0.0"
